version: 1.0.{build}
branches:
  only:
    - master

before_build:
  ps: Install-ChocolateyPackage 'monogame' 'exe' '/S' 'http://www.monogame.net/releases/v3.5.1/MonoGameSetup.exe'
  - nuget restore

build:
  verbosity: minimal
