version: 1.0.{build}
branches:
  only:
    - master

before_build:
  - ps: Invoke-WebRequest 'http://www.monogame.net/releases/v3.5.1/MonoGameSetup.exe' -OutFile 'monogame.exe'
  - monogame.exe /S
  - nuget restore

build:
  verbosity: minimal

notifications:
  - provider: Slack
    incoming_webhook:
      secure: ooAjhsNiQrWMazPqdoAqmXDMe4URwXGgowZMbE/a6l8UHSP1loz1ymVAUppt00KtSViGCO+mwWLvcmVx5KTxVxP1fZVU/ZnbvIKpXcIBxok=